version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passwd
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  job-api:
    container_name: job-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:OevqSZlKgcMHslf0d1VG@database-1.ccaxrfdti3js.ap-southeast-1.rds.amazonaws.com:5432/sand?schema=public
    ports:
      - 5000:5000
    depends_on:
      - db
